services:
  server:
    build:
      context: .
      target: final
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: codecareerix_db
      JWT_SECRET: d37ac51e8bdee8b84c99e5e2ac409e672501d9da9d39b597022699dd7f57eba5

  db:
    image: postgres:16-alpine
    container_name: codecareerix_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codecareerix_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d codecareerix_db"]
      interval: 5s
      retries: 5
      timeout: 5s

volumes:
  postgres_data:
